#ansible-playbook test-playbook.yml --extra-vars "ansible_become_pass=sudo_pass"
#To run without installing software dependencies
#ansible-playbook test-playbook.yml --extra-vars "ansible_become_pass=sudo_pass" --skip-tags "software"
- hosts: localhost

  pre_tasks:
     - raw:  ansible-galaxy role install -r requirements.yml

  vars:
    with_pushes: true
    vars:
      git_chdir: "/{{ host_root_dir }}/{{ repos_dir }}/{{ item.value.repo_git_name }}/{{ item.value.repo_project }}{{ item.value.repo_name }}"
      git_branch: "{{ item.value.repo_git_branch|default('master') }}"
      git_repo_name: "{{ item.value.repo_name }}"


  tasks:
    - name: Including role to test
      include_role:
        name: '../common_git-push'
